export type KPI = {
  label: string;
  value: string;
  delta: string;
  sentiment: 'pos' | 'neg' | 'neu';
};

export type ScenarioTab = {
  kpis: KPI[];
  dataSummary: string;
  [key: string]: any;
};

export type Scenario = {
  name: string;
  company: string;
  tagline: string;
  tabs: Record<string, ScenarioTab>;
};

export const SCENARIOS: Record<string, Scenario> = {
  dtc: {
    name: 'Direct-to-Consumer',
    company: 'Lumé',
    tagline: 'Premium DTC skincare brand, 8 months post-launch',
    tabs: {
      pl: {
        kpis: [
          { label: 'Monthly revenue', value: '£68,400', delta: '+12% MoM', sentiment: 'pos' },
          { label: 'Gross margin', value: '58%', delta: '-3pp vs target', sentiment: 'neg' },
          { label: 'EBITDA', value: '-£14,200', delta: 'Cash negative', sentiment: 'neg' },
          { label: 'Blended CAC', value: '£42', delta: '+£8 vs 6mo ago', sentiment: 'neg' },
          { label: 'LTV:CAC', value: '2.8x', delta: 'Below 3x threshold', sentiment: 'neg' },
        ],
        months: ['Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'],
        revenue: [28,31,34,38,44,52,58,63,68],
        cogs: [13,14,15,17,21,26,28,30,29],
        marketing: [18,19,20,22,24,28,31,33,35],
        ops: [6,6,7,7,8,9,9,10,10],
        dataSummary: 'Revenue £68.4k (+12% MoM). Gross margin 58% (-3pp target). EBITDA -£14.2k. CAC £42 (up £8 in 6mo). LTV:CAC 2.8x (below 3x threshold). Marketing spend has grown from £18k to £35k in 9 months.',
      },
      funnel: {
        kpis: [
          { label: 'Monthly sessions', value: '22,400', delta: '+18% MoM', sentiment: 'pos' },
          { label: 'Add-to-cart rate', value: '14.2%', delta: 'Benchmark: 22%', sentiment: 'neg' },
          { label: 'Checkout CVR', value: '23%', delta: 'Benchmark: 65%', sentiment: 'neg' },
          { label: 'Overall CVR', value: '0.9%', delta: 'Benchmark: 2.5%', sentiment: 'neg' },
          { label: 'AOV', value: '£64', delta: '+£4 vs last Q', sentiment: 'pos' },
        ],
        stages: ['Sessions','Product view','Add to cart','Checkout start','Purchase','Repeat 90d'],
        vals: [22400,11200,3181,1820,420,46],
        bySource: [
          { channel: 'Paid social', sessions: 8200, cvr: '0.7%', aov: '£58', roas: '1.4x' },
          { channel: 'Paid search', sessions: 3800, cvr: '1.8%', aov: '£71', roas: '2.9x' },
          { channel: 'Organic', sessions: 6100, cvr: '1.1%', aov: '£68', roas: '—' },
          { channel: 'Email', sessions: 2800, cvr: '3.2%', aov: '£76', roas: '—' },
        ],
        dataSummary: '22,400 sessions. Add-to-cart 14.2% (benchmark 22%). Checkout CVR 23% (benchmark 65% — 3x gap). Overall CVR 0.9% (benchmark 2.5%). Mobile checkout abandonment 81%. Payment failure rate 11.2%. Email CVR 3.2% is highest converting source.',
      },
      channels: {
        kpis: [
          { label: 'Total spend', value: '£31,200', delta: '46% of revenue', sentiment: 'neg' },
          { label: 'Blended ROAS', value: '2.2x', delta: 'Target: 3.5x', sentiment: 'neg' },
          { label: 'Meta ROAS', value: '1.4x', delta: 'Below breakeven', sentiment: 'neg' },
          { label: 'Google ROAS', value: '2.9x', delta: 'Strongest channel', sentiment: 'pos' },
          { label: 'Email revenue', value: '£8,400', delta: '£0 marginal cost', sentiment: 'pos' },
        ],
        channels: [
          { name: 'Meta Ads', spend: 18400, revenue: 25800, roas: '1.4x', cac: '£58', signal: 'neg' },
          { name: 'Google Search', spend: 6800, revenue: 19700, roas: '2.9x', cac: '£31', signal: 'pos' },
          { name: 'Google Shopping', spend: 4200, revenue: 11300, roas: '2.7x', cac: '£34', signal: 'pos' },
          { name: 'Email/CRM', spend: 0, revenue: 8400, roas: '—', cac: '£0', signal: 'pos' },
          { name: 'TikTok', spend: 1800, revenue: 2900, roas: '1.6x', cac: '£72', signal: 'neg' },
        ],
        dataSummary: 'Meta £18.4k spend 1.4x ROAS (below 1.8x breakeven, creative frequency 7.2 — optimal <3.0). Google Search £6.8k 2.9x ROAS £31 CAC but capped. Email £0 spend £8.4k revenue. TikTok 1.6x ROAS.',
      },
      cohorts: {
        kpis: [
          { label: 'M1 retention', value: '52%', delta: 'Benchmark: 60%', sentiment: 'neg' },
          { label: 'M3 retention', value: '31%', delta: 'Benchmark: 45%', sentiment: 'neg' },
          { label: 'Repeat purchase', value: '11%', delta: 'Benchmark: 35%', sentiment: 'neg' },
          { label: 'Avg orders 12mo', value: '1.4', delta: 'Low frequency', sentiment: 'neg' },
          { label: 'Payback period', value: '5.8mo', delta: 'Target: <3mo', sentiment: 'neg' },
        ],
        cohortMonths: ['Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb'],
        m1: [62,58,54,56,59,61,55,52],
        m2: [44,41,39,40,42,44,38,null],
        m3: [33,31,21,29,32,33,null,null],
        m4: [28,24,null,22,26,null,null,null],
        m5: [22,19,null,18,null,null,null,null],
        m6: [18,null,null,null,null,null,null,null],
        dataSummary: 'M1 52% (benchmark 60%), M3 31% (benchmark 45%), repeat purchase 11% (benchmark 35%), payback 5.8mo (target <3mo). Sep cohort M3 only 21% — worst cohort on record. Cohort curves deteriorating over time.',
      },
      rfm: {
        kpis: [
          { label: 'Total customers', value: '4,200', delta: '8mo since launch', sentiment: 'neu' },
          { label: 'Champions (9%)', value: '378', delta: '41% of revenue', sentiment: 'pos' },
          { label: 'At-Risk (17%)', value: '714', delta: 'Were high value', sentiment: 'neg' },
          { label: 'Promising (24%)', value: '1,008', delta: 'Recent, low freq', sentiment: 'neu' },
          { label: 'New (36%)', value: '1,512', delta: 'Single purchase', sentiment: 'neu' },
        ],
        segments: [
          { name: 'Champions', r:5, f:5, m:5, count: 378, revenue: '£41k', aov: '£108', action: 'Exclusive access, loyalty tier' },
          { name: 'Loyal', r:4, f:4, m:4, count: 462, revenue: '£28k', aov: '£89', action: 'Subscription upsell, referral ask' },
          { name: 'Promising', r:5, f:2, m:3, count: 1008, revenue: '£19k', aov: '£64', action: '2nd purchase incentive' },
          { name: 'At-Risk', r:2, f:4, m:4, count: 714, revenue: '£22k', aov: '£94', action: 'Win-back + time-limited offer' },
          { name: 'New', r:5, f:1, m:2, count: 1512, revenue: '£14k', aov: '£58', action: 'Onboarding + replenishment nudge' },
          { name: 'Hibernating', r:1, f:2, m:2, count: 126, revenue: '£1.8k', aov: '£44', action: 'Suppress or deep discount' },
        ],
        dataSummary: '4,200 customers. Champions 378 (9%) £41k revenue £108 AOV — 41% of revenue. At-Risk 714 (17%) £22k revenue £94 AOV — previously high value, now quiet. New 1,512 (36%) single purchase. Promising 1,008.',
      },
      benchmarks: {
        kpis: [
          { label: 'CVR vs category', value: '0.9% / 2.5%', delta: '3rd quartile', sentiment: 'neg' },
          { label: 'CAC vs category', value: '£42 / £28', delta: '50% above avg', sentiment: 'neg' },
          { label: 'Retention vs cat.', value: '31% / 45%', delta: '-14pp', sentiment: 'neg' },
          { label: 'Gross margin', value: '58% / 62%', delta: '-4pp gap', sentiment: 'neu' },
          { label: 'Email % revenue', value: '12% / 22%', delta: 'Underleveraged', sentiment: 'neg' },
        ],
        metrics: [
          { metric: 'Checkout CVR', company: '23%', category: '65%', top: '82%', gap: 'Severe' },
          { metric: 'Repeat purchase rate', company: '11%', category: '35%', top: '52%', gap: 'Severe' },
          { metric: 'Overall CVR', company: '0.9%', category: '2.5%', top: '4.1%', gap: 'Significant' },
          { metric: 'Blended CAC (£)', company: '42', category: '28', top: '19', gap: 'Significant' },
          { metric: 'LTV:CAC', company: '2.8x', category: '3.8x', top: '6.2x', gap: 'Below threshold' },
          { metric: 'Email rev share', company: '12%', category: '22%', top: '38%', gap: 'Underleveraged' },
          { metric: 'Gross margin', company: '58%', category: '62%', top: '71%', gap: 'Moderate' },
          { metric: 'AOV (£)', company: '64', category: '58', top: '89', gap: 'Above avg' },
        ],
        dataSummary: 'Checkout CVR 23% vs 65% (Severe). Repeat purchase 11% vs 35% (Severe). CVR 0.9% vs 2.5% (Significant). CAC £42 vs £28. LTV:CAC 2.8x vs 3.8x (Below threshold). AOV £64 vs £58 (Above avg — only metric ahead of benchmark).',
      },
    },
  },

  saas: {
    name: 'SaaS & Product Growth',
    company: 'Flowdesk',
    tagline: 'Productivity SaaS, 14 months post-launch',
    tabs: {
      pl: {
        kpis: [
          { label: 'MRR', value: '£84,200', delta: '+6% MoM', sentiment: 'pos' },
          { label: 'Churn rate', value: '6.2%', delta: 'Target: <3%', sentiment: 'neg' },
          { label: 'NRR', value: '88%', delta: 'Below 100% floor', sentiment: 'neg' },
          { label: 'Gross margin', value: '72%', delta: 'On target', sentiment: 'pos' },
          { label: 'Monthly burn', value: '-£22,000', delta: '11mo runway', sentiment: 'neg' },
        ],
        months: ['Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar','Apr'],
        mrr: [24,28,32,36,41,46,52,58,64,68,72,76,80,84],
        newMrr: [8,9,9,10,11,12,13,14,14,12,13,14,15,16],
        churnedMrr: [2,3,3,4,5,5,6,7,7,8,8,9,10,11],
        expenses: [62,64,66,68,72,76,80,86,90,94,96,98,100,106],
        dataSummary: 'MRR £84.2k (+6% MoM). Churn 6.2% (target <3%). NRR 88% (below 100% floor — contraction outpacing expansion). Gross margin 72%. Monthly burn -£22k with 11mo runway. New MRR £16k offset by £11k churned MRR.',
      },
      funnel: {
        kpis: [
          { label: 'Monthly signups', value: '3,200', delta: '+14% MoM', sentiment: 'pos' },
          { label: 'Activation rate', value: '31%', delta: 'Benchmark: 60%', sentiment: 'neg' },
          { label: 'Trial-to-paid', value: '8%', delta: 'Benchmark: 22%', sentiment: 'neg' },
          { label: 'Time to value', value: '4.2 days', delta: 'Target: <1 day', sentiment: 'neg' },
          { label: 'Team invite rate', value: '9%', delta: 'Benchmark: 30%', sentiment: 'neg' },
        ],
        stages: ['Signup','Email verified','First task','Team invite','Project complete','Paid'],
        vals: [3200,2688,1152,288,198,256],
        activationInsight: {
          completedOnboarding: { cvr: '34%', label: 'Full onboarding completers' },
          droppedOff: { cvr: '3%', label: 'Onboarding dropoffs' },
          liftMultiple: '11.3x',
        },
        bySource: [
          { channel: 'Organic search', signups: 1120, activation: '38%', trialToPaid: '11%', ltv: '£420' },
          { channel: 'Paid social', signups: 840, activation: '18%', trialToPaid: '4%', ltv: '£180' },
          { channel: 'Referral', signups: 560, activation: '52%', trialToPaid: '22%', ltv: '£680' },
          { channel: 'Product Hunt / viral', signups: 420, activation: '24%', trialToPaid: '6%', ltv: '£240' },
          { channel: 'Content / blog', signups: 260, activation: '41%', trialToPaid: '14%', ltv: '£510' },
        ],
        dataSummary: '3,200 signups. Email verified 2,688 (84%). First task 1,152 (36%). Team invite 288 (9%). Project complete 198 (6.2%). Paid 256 (8%). Users completing full onboarding convert at 34% vs 3% for dropoffs (11.3x lift). Referral signups convert at 22% vs 4% paid social.',
      },
      channels: {
        kpis: [
          { label: 'Total spend', value: '£28,400', delta: '34% of new MRR', sentiment: 'neg' },
          { label: 'Blended CAC', value: '£111', delta: 'Target: <£80', sentiment: 'neg' },
          { label: 'Paid social CAC', value: '£142', delta: '0.8x ROAS', sentiment: 'neg' },
          { label: 'Referral CAC', value: '£8', delta: 'Best channel', sentiment: 'pos' },
          { label: 'Referral participation', value: '8%', delta: 'Benchmark: 25%', sentiment: 'neg' },
        ],
        channels: [
          { name: 'Paid social', spend: 14200, newUsers: 840, cac: '£142', roas: '0.8x', ltv: '£180', signal: 'neg' },
          { name: 'Google Ads', spend: 8600, newUsers: 620, cac: '£62', roas: '2.1x', ltv: '£410', signal: 'pos' },
          { name: 'Content/SEO', spend: 4800, newUsers: 1120, cac: '£38', roas: '3.4x', ltv: '£420', signal: 'pos' },
          { name: 'Referral', spend: 800, newUsers: 560, cac: '£8', roas: '18x', ltv: '£680', signal: 'pos' },
          { name: 'Product Hunt / viral', spend: 0, newUsers: 420, cac: '£0', roas: '—', ltv: '£240', signal: 'neu' },
        ],
        dataSummary: 'Paid social £14.2k spend £142 CAC 0.8x ROAS (below breakeven). Google Ads £8.6k £62 CAC 2.1x ROAS. Content/SEO £4.8k £38 CAC 3.4x ROAS. Referral £8 CAC 18x ROAS but only 8% participation (benchmark 25%). Referral users have 3.8x higher LTV than paid social.',
      },
      cohorts: {
        kpis: [
          { label: 'M1 retention', value: '72%', delta: 'Benchmark: 80%', sentiment: 'neg' },
          { label: 'M3 retention', value: '41%', delta: 'Benchmark: 55%', sentiment: 'neg' },
          { label: 'M6 retention', value: '29%', delta: 'Benchmark: 40%', sentiment: 'neg' },
          { label: 'Median lifespan', value: '4.2mo', delta: 'Target: 12mo+', sentiment: 'neg' },
          { label: 'Expansion rate', value: '4%', delta: 'Target: 15%', sentiment: 'neg' },
        ],
        cohortMonths: ['Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb'],
        m1: [78,76,75,74,73,74,72,71,72,73,72,72],
        m2: [58,56,54,53,52,51,50,49,48,48,47,null],
        m3: [46,44,43,42,42,41,40,39,41,41,null,null],
        m4: [38,36,35,34,34,33,33,32,34,null,null,null],
        m5: [33,31,30,30,29,29,30,29,null,null,null,null],
        m6: [29,28,27,27,28,29,29,null,null,null,null,null],
        dataSummary: 'M1 72% (benchmark 80%), M3 41% (benchmark 55%), M6 29% (benchmark 40%). Median user lifespan 4.2mo (target 12mo+). Expansion rate only 4% (target 15%). Biggest drop at M1→M2 (72%→47%), suggesting value delivery gap after initial use.',
      },
      rfm: {
        kpis: [
          { label: 'Total users', value: '1,830', delta: '14mo since launch', sentiment: 'neu' },
          { label: 'Power users (8%)', value: '146', delta: '41% of MRR', sentiment: 'pos' },
          { label: 'At-Risk (22%)', value: '400', delta: '71% churn in 60d', sentiment: 'neg' },
          { label: 'Active (28%)', value: '520', delta: 'Stable engagement', sentiment: 'pos' },
          { label: 'Dormant (21%)', value: '384', delta: 'No login 30d+', sentiment: 'neg' },
        ],
        segments: [
          { name: 'Power users', r:5, f:5, m:5, count: 146, mrrShare: '41%', avgPlan: '£48/mo', action: 'Beta access, advisory board, case studies' },
          { name: 'Active', r:4, f:3, m:3, count: 520, mrrShare: '32%', avgPlan: '£28/mo', action: 'Feature adoption nudges, team invite prompt' },
          { name: 'Trial', r:5, f:1, m:1, count: 380, mrrShare: '0%', avgPlan: 'Free', action: 'Onboarding acceleration, time-to-value reduction' },
          { name: 'At-Risk', r:2, f:3, m:3, count: 400, mrrShare: '19%', avgPlan: '£22/mo', action: 'Re-engagement campaign, success call, rescue offer' },
          { name: 'Dormant', r:1, f:2, m:2, count: 384, mrrShare: '8%', avgPlan: '£14/mo', action: 'Win-back email sequence, sunset after 90d' },
        ],
        dataSummary: '1,830 users. Power users 146 (8%) drive 41% of MRR at £48/mo avg. At-Risk 400 (22%) — 71% will churn within 60d if unreached, representing £19% of MRR. Active 520 (28%) stable. Trial 380 (21%) unconverted. Dormant 384 (21%) no login 30d+.',
      },
      benchmarks: {
        kpis: [
          { label: 'Trial-to-paid', value: '8% / 22%', delta: 'Severe gap', sentiment: 'neg' },
          { label: 'Activation rate', value: '31% / 60%', delta: 'Severe gap', sentiment: 'neg' },
          { label: 'Monthly churn', value: '6.2% / 3%', delta: '2x benchmark', sentiment: 'neg' },
          { label: 'NRR', value: '88% / 115%', delta: '-27pp gap', sentiment: 'neg' },
          { label: 'Gross margin', value: '72% / 75%', delta: 'Acceptable', sentiment: 'neu' },
        ],
        metrics: [
          { metric: 'Trial-to-paid CVR', company: '8%', category: '22%', top: '38%', gap: 'Severe' },
          { metric: 'Activation rate', company: '31%', category: '60%', top: '78%', gap: 'Severe' },
          { metric: 'Monthly churn', company: '6.2%', category: '3.0%', top: '1.2%', gap: 'Significant' },
          { metric: 'Net revenue retention', company: '88%', category: '115%', top: '135%', gap: 'Significant' },
          { metric: 'CAC payback (mo)', company: '8.4', category: '5', top: '3', gap: 'Significant' },
          { metric: 'Expansion rate', company: '4%', category: '15%', top: '28%', gap: 'Significant' },
          { metric: 'Gross margin', company: '72%', category: '75%', top: '85%', gap: 'Moderate' },
          { metric: 'DAU/MAU ratio', company: '14%', category: '25%', top: '42%', gap: 'Significant' },
        ],
        dataSummary: 'Trial-to-paid 8% vs 22% (Severe). Activation 31% vs 60% (Severe). Monthly churn 6.2% vs 3% (Significant — 2x benchmark). NRR 88% vs 115% (Significant — contraction outpacing expansion). CAC payback 8.4mo vs 5mo. DAU/MAU 14% vs 25%.',
      },
    },
  },

  market: {
    name: 'Marketplace Economics',
    company: 'Stackd',
    tagline: 'Freelance services marketplace, 10 months live',
    tabs: {
      pl: {
        kpis: [
          { label: 'GMV', value: '£82,000/mo', delta: '+9% MoM', sentiment: 'pos' },
          { label: 'Take rate', value: '18%', delta: 'On target', sentiment: 'pos' },
          { label: 'Net revenue', value: '£14,800', delta: 'From GMV', sentiment: 'neu' },
          { label: 'Monthly burn', value: '-£8,200', delta: '14mo runway', sentiment: 'neg' },
          { label: 'Unit economics', value: '£43 LTV', delta: 'Buyer avg', sentiment: 'neu' },
        ],
        months: ['Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'],
        gmv: [18,24,32,40,48,54,62,68,74,82],
        netRevenue: [3.2,4.3,5.8,7.2,8.6,9.7,11.2,12.2,13.3,14.8],
        opex: [16,17,18,19,20,21,22,22,23,23],
        sellers: [280,380,480,580,680,780,880,980,1080,1200],
        buyers: [48,68,92,120,152,184,218,256,298,340],
        dataSummary: 'GMV £82k/mo (+9% MoM). Take rate 18%. Net revenue £14.8k. Monthly burn -£8.2k (14mo runway). 1,200 sellers, 340 buyers. Supply significantly outpacing demand. GMV growth decelerating from 33% to 9% MoM.',
      },
      funnel: {
        kpis: [
          { label: 'Briefs posted', value: '340/mo', delta: '+11% MoM', sentiment: 'pos' },
          { label: 'Proposals received', value: '80%', delta: 'Healthy supply', sentiment: 'pos' },
          { label: 'Hire rate', value: '52%', delta: 'From brief to hire', sentiment: 'neu' },
          { label: 'Time to first hire', value: '8.4 days', delta: 'Benchmark: 3d', sentiment: 'neg' },
          { label: 'Repeat hire rate', value: '22%', delta: 'Benchmark: 55%', sentiment: 'neg' },
        ],
        stages: ['Brief posted','Proposals received','Shortlist','Interview','Hire'],
        vals: [340,272,190,136,176],
        timeMetrics: [
          { step: 'Brief → first proposal', avgTime: '2.1d', benchmark: '4h', status: 'slow' },
          { step: 'Proposal → shortlist', avgTime: '3.2d', benchmark: '1d', status: 'slow' },
          { step: 'Shortlist → interview', avgTime: '1.8d', benchmark: '1d', status: 'ok' },
          { step: 'Interview → hire', avgTime: '1.3d', benchmark: '1d', status: 'ok' },
        ],
        byCategory: [
          { category: 'Design', briefs: 112, hireRate: '61%', avgValue: '£380', ttHire: '6.2d' },
          { category: 'Development', briefs: 88, hireRate: '48%', avgValue: '£620', ttHire: '11.4d' },
          { category: 'Marketing', briefs: 74, hireRate: '54%', avgValue: '£290', ttHire: '7.8d' },
          { category: 'Writing', briefs: 66, hireRate: '42%', avgValue: '£180', ttHire: '9.1d' },
        ],
        dataSummary: 'Briefs posted 340/mo. Proposals received 272 (80%). Shortlist 190 (56%). Interview 136 (40%). Hire 176 (52%). Time to first hire 8.4d (benchmark 3d — 2.8x slower). Brief→first proposal takes 2.1d vs 4h benchmark. Design highest hire rate 61%, Development slowest at 11.4d.',
      },
      channels: {
        kpis: [
          { label: 'Total spend', value: '£4,200', delta: '28% of net rev', sentiment: 'neg' },
          { label: 'Organic share', value: '42%', delta: 'Of new buyers', sentiment: 'pos' },
          { label: 'Paid buyer CAC', value: '£38', delta: 'Vs £43 LTV', sentiment: 'neg' },
          { label: 'Referral hire rate', value: '28%', delta: 'Vs 9% paid', sentiment: 'pos' },
          { label: 'Seller CPA', value: '£1.20', delta: 'Oversupplied', sentiment: 'neu' },
        ],
        channels: [
          { name: 'Organic / SEO', spend: 0, newBuyers: 143, cac: '£0', hireRate: '18%', signal: 'pos' },
          { name: 'Paid social', spend: 2400, newBuyers: 64, cac: '£38', hireRate: '9%', signal: 'neg' },
          { name: 'Referral (buyer)', spend: 600, newBuyers: 78, cac: '£8', hireRate: '28%', signal: 'pos' },
          { name: 'Google Ads', spend: 1200, newBuyers: 42, cac: '£29', hireRate: '14%', signal: 'neu' },
          { name: 'Partnerships', spend: 0, newBuyers: 13, cac: '£0', hireRate: '31%', signal: 'pos' },
        ],
        dataSummary: 'Total spend £4.2k (28% of net revenue). Organic 42% of new buyers. Paid social £38 CAC with only 9% hire rate (barely above LTV). Referral buyers hire at 28% vs 9% paid (3x better) but only 8% of buyers ever share. Seller acquisition essentially free — supply problem is quality, not quantity.',
      },
      cohorts: {
        kpis: [
          { label: 'Active buyers', value: '340', delta: '+11% MoM', sentiment: 'pos' },
          { label: 'Active sellers', value: '1,200', delta: 'Supply heavy', sentiment: 'neg' },
          { label: 'Buyer:seller ratio', value: '0.28', delta: 'Target: 0.8', sentiment: 'neg' },
          { label: 'GMV per seller', value: '£68/mo', delta: 'Below £200 min', sentiment: 'neg' },
          { label: 'Repeat hire rate', value: '22%', delta: 'Benchmark: 55%', sentiment: 'neg' },
        ],
        cohortMonths: ['Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'],
        buyerM1: [58,54,52,48,46,44,42,40,38,36],
        buyerM2: [38,35,33,31,29,28,26,24,22,null],
        buyerM3: [26,24,22,20,19,18,17,16,null,null],
        sellerM1: [82,80,78,76,74,72,71,70,68,66],
        sellerM3: [48,46,44,42,40,38,36,34,null,null],
        sellerM6: [22,20,18,17,16,null,null,null,null,null],
        dataSummary: '340 active buyers, 1,200 sellers. Buyer:seller ratio 0.28 (target 0.8). GMV per seller £68/mo (below £200 threshold for seller viability). Repeat hire 22% (benchmark 55%). Buyer M1 retention declining from 58% to 36%. Seller churn accelerating as earnings disappoint.',
      },
      rfm: {
        kpis: [
          { label: 'Total buyers', value: '340', delta: 'Active monthly', sentiment: 'neu' },
          { label: 'HV Regulars (12%)', value: '41', delta: '48% of GMV', sentiment: 'pos' },
          { label: 'At-Risk (19%)', value: '65', delta: 'Declining frequency', sentiment: 'neg' },
          { label: 'First-timers (28%)', value: '95', delta: 'Single transaction', sentiment: 'neu' },
          { label: 'Churned (17%)', value: '57', delta: 'No activity 60d+', sentiment: 'neg' },
        ],
        segments: [
          { name: 'HV Regulars', r:5, f:5, m:5, count: 41, gmvShare: '48%', avgMonthlyGMV: '£960', action: 'Account manager, priority matching, loyalty pricing' },
          { name: 'Occasionals', r:3, f:3, m:3, count: 82, gmvShare: '24%', avgMonthlyGMV: '£240', action: 'Proactive brief suggestions, category expansion' },
          { name: 'First-timers', r:5, f:1, m:2, count: 95, gmvShare: '14%', avgMonthlyGMV: '£120', action: 'Concierge matching, satisfaction follow-up' },
          { name: 'At-Risk', r:2, f:3, m:3, count: 65, gmvShare: '11%', avgMonthlyGMV: '£140', action: 'Re-engagement, quality guarantee, credit offer' },
          { name: 'Churned', r:1, f:1, m:2, count: 57, gmvShare: '3%', avgMonthlyGMV: '£0', action: 'Win-back survey, new seller showcase' },
        ],
        dataSummary: '340 buyers. HV Regulars 41 (12%) drive 48% of GMV at £960/mo avg. Occasionals 82 (24%) at £240/mo. First-timers 95 (28%) single transaction. At-Risk 65 (19%) declining frequency. Churned 57 (17%). Top 12% of buyers drive nearly half of all GMV.',
      },
      benchmarks: {
        kpis: [
          { label: 'Buyer:seller ratio', value: '0.28 / 0.8', delta: '3x below target', sentiment: 'neg' },
          { label: 'Repeat hire rate', value: '22% / 55%', delta: '-33pp gap', sentiment: 'neg' },
          { label: 'Time to hire', value: '8.4d / 3d', delta: '2.8x slower', sentiment: 'neg' },
          { label: 'Take rate', value: '18% / 15%', delta: 'Above avg', sentiment: 'pos' },
          { label: 'GMV per seller', value: '£68 / £200', delta: 'Below viable', sentiment: 'neg' },
        ],
        metrics: [
          { metric: 'Buyer:seller ratio', company: '0.28', category: '0.8', top: '1.2', gap: 'Severe' },
          { metric: 'Repeat hire rate', company: '22%', category: '55%', top: '72%', gap: 'Severe' },
          { metric: 'Time to first hire', company: '8.4d', category: '3d', top: '1d', gap: 'Significant' },
          { metric: 'Buyer M1 retention', company: '36%', category: '55%', top: '72%', gap: 'Significant' },
          { metric: 'GMV per seller (£/mo)', company: '68', category: '200', top: '480', gap: 'Severe' },
          { metric: 'Take rate', company: '18%', category: '15%', top: '22%', gap: 'Above avg' },
          { metric: 'Brief-to-hire rate', company: '52%', category: '60%', top: '78%', gap: 'Moderate' },
          { metric: 'NPS (buyer)', company: '28', category: '42', top: '62', gap: 'Significant' },
        ],
        dataSummary: 'Buyer:seller ratio 0.28 vs 0.8 (Severe — 3x below target). Repeat hire 22% vs 55% (Severe). Time to hire 8.4d vs 3d (Significant — 2.8x slower). GMV per seller £68 vs £200 (Severe). Take rate 18% vs 15% (Above avg — one bright spot). NPS 28 vs 42.',
      },
    },
  },

  media: {
    name: 'Media & Monetisation',
    company: 'The Brief',
    tagline: 'B2B marketing newsletter, 18 months old',
    tabs: {
      pl: {
        kpis: [
          { label: 'Monthly revenue', value: '£18,200', delta: '+4% MoM', sentiment: 'pos' },
          { label: 'Sponsor concentration', value: '92%', delta: 'High risk', sentiment: 'neg' },
          { label: 'Total subscribers', value: '18,400', delta: '+6% MoM', sentiment: 'pos' },
          { label: 'Revenue per sub', value: '£0.99', delta: 'Benchmark: £2.50', sentiment: 'neg' },
          { label: 'Operating margin', value: '38%', delta: 'Healthy', sentiment: 'pos' },
        ],
        months: ['Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'],
        subscribers: [4200,5100,6200,7400,8600,9800,10800,11600,12400,13200,14000,15200,16000,16800,17200,17600,18000,18400],
        revenue: [2.8,3.6,4.8,6.2,7.4,8.6,9.8,10.4,11.2,12.4,13.8,15.2,16.0,16.8,17.2,17.4,17.8,18.2],
        sponsorRevenue: [2.8,3.6,4.8,6.0,7.0,8.0,9.2,9.8,10.4,11.4,12.6,14.0,14.8,15.6,15.8,16.0,16.4,16.7],
        otherRevenue: [0,0,0,0.2,0.4,0.6,0.6,0.6,0.8,1.0,1.2,1.2,1.2,1.2,1.4,1.4,1.4,1.5],
        dataSummary: 'Revenue £18.2k/mo (+4% MoM, decelerating). 92% from sponsors (concentration risk — top 3 sponsors = 64% of revenue). 18,400 subscribers. Revenue per sub £0.99 (benchmark £2.50). Growth has slowed from 22% to 4% MoM.',
      },
      funnel: {
        kpis: [
          { label: 'Open rate', value: '44%', delta: 'Declining trend', sentiment: 'neg' },
          { label: 'CTOR', value: '7%', delta: 'Benchmark: 18-22%', sentiment: 'neg' },
          { label: 'Sponsor CTR', value: '0.8%', delta: 'Sponsors want 2%+', sentiment: 'neg' },
          { label: 'Unsub rate', value: '0.9%', delta: 'Benchmark: 0.3%', sentiment: 'neg' },
          { label: 'List growth rate', value: '6%', delta: 'Net of unsubs', sentiment: 'neu' },
        ],
        stages: ['Subscribers','Opens','Clicks (CTOR)','Link clicks','Sponsor clicks'],
        vals: [18400,8096,567,284,64],
        openRateTrend: {
          months: ['Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'],
          rates: [52,51,50,48,47,46,45,44,44],
        },
        bySegment: [
          { segment: 'Loyal openers', subs: 3312, openRate: '82%', ctor: '14%', sponsorCtr: '2.4%' },
          { segment: 'Occasional', subs: 5520, openRate: '38%', ctor: '6%', sponsorCtr: '0.6%' },
          { segment: 'Ghosts', subs: 7360, openRate: '0%', ctor: '0%', sponsorCtr: '0%' },
          { segment: 'New (<90d)', subs: 2208, openRate: '58%', ctor: '9%', sponsorCtr: '1.2%' },
        ],
        dataSummary: 'Subscribers 18,400. Opens 8,096 (44%, declining from 52% over 8 months). CTOR 7% (benchmark 18-22% — severe gap). Sponsor CTR 0.8% (sponsors expect 2%+). Unsub 0.9% (benchmark 0.3% — 3x above). Ghosts 7,360 (40%) dragging all metrics. Loyal openers 3,312 (18%) deliver 2.4% sponsor CTR.',
      },
      channels: {
        kpis: [
          { label: 'Total sub cost', value: '£2,800/mo', delta: 'Blended CPS £1.40', sentiment: 'neu' },
          { label: 'Referral CPS', value: '£0.80', delta: 'Best channel', sentiment: 'pos' },
          { label: 'Paid social CPS', value: '£6.40', delta: '8x referral cost', sentiment: 'neg' },
          { label: 'Referral open rate', value: '61%', delta: 'Vs 31% paid', sentiment: 'pos' },
          { label: 'Referral participation', value: '8%', delta: 'Benchmark: 25%', sentiment: 'neg' },
        ],
        channels: [
          { name: 'Organic / word-of-mouth', spend: 0, newSubs: 420, cps: '£0', openRate: '54%', signal: 'pos' },
          { name: 'Referral program', spend: 480, newSubs: 600, cps: '£0.80', openRate: '61%', signal: 'pos' },
          { name: 'Cross-promotions', spend: 320, newSubs: 380, cps: '£0.84', openRate: '48%', signal: 'pos' },
          { name: 'Content / SEO', spend: 400, newSubs: 240, cps: '£1.67', openRate: '52%', signal: 'neu' },
          { name: 'Paid social', spend: 1200, newSubs: 188, cps: '£6.40', openRate: '31%', signal: 'neg' },
          { name: 'Paid newsletter ads', spend: 400, newSubs: 172, cps: '£2.33', openRate: '42%', signal: 'neu' },
        ],
        dataSummary: 'Referral CPS £0.80 vs paid social £6.40 (8x cheaper). Referral subs open at 61% vs paid 31% (2x engagement). But only 8% participation rate (benchmark 25%). Paid social subs have 31% open rate — many become ghosts. Cross-promotions £0.84 CPS with 48% open rate.',
      },
      cohorts: {
        kpis: [
          { label: 'Open rate M1', value: '62%', delta: 'Healthy start', sentiment: 'pos' },
          { label: 'Open rate M6', value: '44%', delta: '-18pp decay', sentiment: 'neg' },
          { label: 'Open rate M12', value: '32%', delta: '-30pp decay', sentiment: 'neg' },
          { label: 'Unsub rate', value: '0.9%/issue', delta: 'Benchmark: 0.3%', sentiment: 'neg' },
          { label: 'Ghost rate (>90d)', value: '40%', delta: 'Of total list', sentiment: 'neg' },
        ],
        cohortMonths: ['Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'],
        openM1: [64,63,62,62,61,60,62,63,62,61,62,62],
        openM3: [52,51,50,50,48,48,47,48,47,46,null,null],
        openM6: [44,43,42,42,41,40,null,null,null,null,null,null],
        openM9: [36,35,34,null,null,null,null,null,null,null,null,null],
        openM12: [32,null,null,null,null,null,null,null,null,null,null,null],
        unsubByMonth: [0.4,0.5,0.5,0.6,0.6,0.7,0.7,0.8,0.8,0.8,0.9,0.9],
        dataSummary: 'Open rate declines from 62% M1 to 44% M6 to 32% M12. Unsub rate rising from 0.4% to 0.9% per issue (benchmark 0.3%). Ghost rate 40% of list. Open rate declining across all cohorts over 8 months — not just a cohort mix issue, engagement is dropping everywhere.',
      },
      rfm: {
        kpis: [
          { label: 'Total subscribers', value: '18,400', delta: '18mo old list', sentiment: 'neu' },
          { label: 'Loyal openers (18%)', value: '3,312', delta: '71% of clicks', sentiment: 'pos' },
          { label: 'Ghosts (40%)', value: '7,360', delta: 'No opens 90d+', sentiment: 'neg' },
          { label: 'Occasional (30%)', value: '5,520', delta: 'Irregular opens', sentiment: 'neu' },
          { label: 'New (12%)', value: '2,208', delta: '<90 days old', sentiment: 'pos' },
        ],
        segments: [
          { name: 'Loyal openers', r:5, f:5, m:5, count: 3312, openRate: '82%', clickShare: '71%', sponsorCtr: '2.4%', action: 'Premium tier, exclusive content, referral program focus' },
          { name: 'Occasional', r:3, f:3, m:3, count: 5520, openRate: '38%', clickShare: '18%', sponsorCtr: '0.6%', action: 'Subject line testing, send time optimization, re-engagement' },
          { name: 'New (<90d)', r:5, f:2, m:2, count: 2208, openRate: '58%', clickShare: '9%', sponsorCtr: '1.2%', action: 'Welcome sequence, expectation setting, early habit formation' },
          { name: 'Ghosts', r:1, f:1, m:1, count: 7360, openRate: '0%', clickShare: '0%', sponsorCtr: '0%', action: 'Sunset campaign: re-confirm or remove after 30d' },
        ],
        dataSummary: '18,400 subscribers. Loyal openers 3,312 (18%) generate 71% of all sponsor clicks with 2.4% CTR. Occasional 5,520 (30%) at 0.6% sponsor CTR. Ghosts 7,360 (40%) — zero engagement, inflating list, deflating rates. New 2,208 (12%) at 58% open rate. Removing ghosts would lift open rate from 44% to 73%.',
      },
      benchmarks: {
        kpis: [
          { label: 'Open rate', value: '44% / 42%', delta: 'Slight strength', sentiment: 'pos' },
          { label: 'CTOR', value: '7% / 18-22%', delta: 'Severe gap', sentiment: 'neg' },
          { label: 'Referral rate', value: '8% / 25%', delta: '-17pp gap', sentiment: 'neg' },
          { label: 'Unsub rate', value: '0.9% / 0.3%', delta: '3x benchmark', sentiment: 'neg' },
          { label: 'Rev per sub', value: '£0.99 / £2.50', delta: '60% below avg', sentiment: 'neg' },
        ],
        metrics: [
          { metric: 'Open rate', company: '44%', category: '42%', top: '55%', gap: 'At par' },
          { metric: 'CTOR', company: '7%', category: '18%', top: '28%', gap: 'Severe' },
          { metric: 'Sponsor CTR', company: '0.8%', category: '2.0%', top: '3.5%', gap: 'Severe' },
          { metric: 'Referral participation', company: '8%', category: '25%', top: '42%', gap: 'Significant' },
          { metric: 'Unsub rate (per issue)', company: '0.9%', category: '0.3%', top: '0.1%', gap: 'Severe' },
          { metric: 'Revenue per sub (£/mo)', company: '0.99', category: '2.50', top: '4.80', gap: 'Significant' },
          { metric: 'Sponsor concentration', company: '92%', category: '60%', top: '40%', gap: 'Severe' },
          { metric: 'List growth rate (net)', company: '6%', category: '12%', top: '22%', gap: 'Moderate' },
        ],
        dataSummary: 'Open rate 44% vs 42% (At par — only metric at benchmark). CTOR 7% vs 18-22% (Severe — content drives opens but not clicks). Sponsor CTR 0.8% vs 2.0% (Severe — threatens sponsor renewals). Unsub 0.9% vs 0.3% (Severe — 3x benchmark). Referral 8% vs 25%. Revenue per sub £0.99 vs £2.50.',
      },
    },
  },
  ecom: {
    name: 'Future of E-commerce',
    company: 'Spark',
    tagline: 'Social-first beauty brand, TikTok-native, 2yr old. Platform fees rising from 2% to 8%.',
    tabs: {
      pl: {
        kpis: [
          { label: 'Annual GMV', value: '£4.2M', delta: '+34% YoY', sentiment: 'pos' },
          { label: 'Gross margin', value: '52%', delta: '-6pp vs target', sentiment: 'neg' },
          { label: 'EBITDA', value: '-£180k', delta: 'Cash negative', sentiment: 'neg' },
          { label: 'Blended CAC', value: '£18', delta: '+£7 vs prior year', sentiment: 'neg' },
          { label: 'Platform fee cost', value: '£262k', delta: '8% of GMV (was 2%)', sentiment: 'neg' },
        ],
        months: ['May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan'],
        revenue:   [28,32,38,44,51,58,71,89,62],
        cogs:      [13,15,18,21,25,28,35,44,30],
        marketing: [9,11,14,16,19,22,27,31,24],
        ops:       [4,5,5,6,7,8,9,11,8],
        dataSummary: 'Annual GMV £4.2M (+34% YoY). Gross margin 52% (-6pp vs 58% target). EBITDA -£180k — cash negative despite strong revenue growth. Blended CAC £18 (up from £11 prior year). Platform fees increased from 2% to 8% of GMV — adding £262k in annualised cost. Marketing spend grown from £9k to £24k/month in 9 months as TikTok organic reach declines.',
      },
      funnel: {
        kpis: [
          { label: 'TikTok views', value: '18.4M', delta: '+22% MoM', sentiment: 'pos' },
          { label: 'TikTok Shop CVR', value: '3.1%', delta: 'Benchmark: 2.8%', sentiment: 'pos' },
          { label: 'DTC website CVR', value: '0.4%', delta: 'Benchmark: 2.2%', sentiment: 'neg' },
          { label: 'Email capture rate', value: '6.2%', delta: 'Benchmark: 14%', sentiment: 'neg' },
          { label: 'Repeat purchase', value: '19%', delta: 'Benchmark: 38%', sentiment: 'neg' },
        ],
        stages: [
          { label: 'TikTok views', value: 18400000 },
          { label: 'Profile clicks', value: 920000 },
          { label: 'TikTok Shop visits', value: 368000 },
          { label: 'Add to basket', value: 88320 },
          { label: 'TikTok purchase', value: 11418 },
          { label: 'DTC website visit', value: 184000 },
          { label: 'DTC purchase', value: 736 },
        ],
        bySource: [
          { channel: 'TikTok Shop', sessions: 368000, cvr: '3.1%', aov: '£28', roas: '4.2x' },
          { channel: 'DTC website', sessions: 184000, cvr: '0.4%', aov: '£41', roas: '1.1x' },
          { channel: 'Instagram', sessions: 42000, cvr: '0.8%', aov: '£36', roas: '1.4x' },
          { channel: 'Email', sessions: 18000, cvr: '2.1%', aov: '£44', roas: '—' },
        ],
        dataSummary: '18.4M TikTok views (+22% MoM). TikTok Shop CVR 3.1% — above the 2.8% platform benchmark. DTC website CVR 0.4% vs 2.2% benchmark — a 5x gap. Email capture rate 6.2% vs 14% benchmark. Repeat purchase rate 19% vs 38% benchmark. DTC AOV £41 vs TikTok AOV £28 — customers who reach the DTC site spend 46% more per order.',
      },
      channels: {
        kpis: [
          { label: 'Total channel spend', value: '£288k', delta: '6.9% of GMV', sentiment: 'neu' },
          { label: 'TikTok Shop revenue', value: '£3.28M', delta: '78% of GMV', sentiment: 'neg' },
          { label: 'DTC website revenue', value: '£594k', delta: '14% of GMV', sentiment: 'pos' },
          { label: 'Platform fee total', value: '£262k', delta: 'Rising 4x YoY', sentiment: 'neg' },
          { label: 'Owned channel share', value: '18%', delta: 'Target: 40%', sentiment: 'neg' },
        ],
        channels: [
          { name: 'TikTok Shop (organic)', spend: 0, revenue: 2100000, roas: '—', cac: '£0', signal: 'pos' },
          { name: 'TikTok Shop (paid promo)', spend: 168000, revenue: 1180000, roas: '7.0x', cac: '£14', signal: 'pos' },
          { name: 'DTC website (paid)', spend: 84000, revenue: 594000, roas: '1.1x', cac: '£114', signal: 'neg' },
          { name: 'Instagram Shopping', spend: 24000, revenue: 218000, roas: '1.4x', cac: '£57', signal: 'neu' },
          { name: 'Email / CRM', spend: 12000, revenue: 108000, roas: '—', cac: '£0', signal: 'pos' },
        ],
        dataSummary: '78% of GMV through TikTok Shop. Organic TikTok drives £2.1M at zero direct cost. DTC website only 14% of GMV, ROAS 1.1x — barely breaking even on paid traffic. Platform fee total £262k. Email generates £108k at near-zero marginal cost but only 18k subscribers. DTC CAC £114 vs TikTok CAC £14 — owned channel is 8x more expensive to drive traffic to.',
      },
      cohorts: {
        kpis: [
          { label: 'M1 retention', value: '41%', delta: 'Benchmark: 55%', sentiment: 'neg' },
          { label: 'M3 retention', value: '19%', delta: 'Benchmark: 38%', sentiment: 'neg' },
          { label: 'TikTok buyer repeat', value: '14%', delta: 'Platform avg: 22%', sentiment: 'neg' },
          { label: 'DTC buyer repeat', value: '38%', delta: 'At benchmark', sentiment: 'pos' },
          { label: 'Email subscriber LTV', value: '£94', delta: 'vs £28 avg', sentiment: 'pos' },
        ],
        cohortMonths: ['May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
        m1: [44,42,41,39,38,40,43,41],
        m2: [28,27,26,24,23,25,28,null],
        m3: [22,20,19,18,17,19,null,null],
        m4: [17,16,14,13,12,null,null,null],
        m5: [13,12,10,9,null,null,null,null],
        m6: [10,9,null,null,null,null,null,null],
        dataSummary: 'M1 retention 41% (benchmark 55%), M3 19% (benchmark 38%). TikTok buyers repeat at only 14% — below the 22% TikTok platform average. DTC buyers repeat at 38% — at benchmark, 2.7x higher than TikTok buyers. Email subscribers have LTV of £94 vs £28 average customer LTV — 3.4x higher. Cohort curves declining from May as TikTok audience quality deteriorates with paid promotion scaling.',
      },
      rfm: {
        kpis: [
          { label: 'Total customers', value: '148k', delta: '2 years trading', sentiment: 'neu' },
          { label: 'DTC registered', value: '9,200', delta: '6.2% of base', sentiment: 'neg' },
          { label: 'Email subscribers', value: '18k', delta: '12% of base', sentiment: 'neg' },
          { label: 'High-LTV segment', value: '4,100', delta: 'AOV £94, repeat 38%', sentiment: 'pos' },
          { label: 'Platform-only', value: '121k', delta: 'No email, no DTC', sentiment: 'neg' },
        ],
        segments: [
          { name: 'Owned Champions', count: 4100, revenue: '£385k', aov: '£94', action: 'Loyalty programme, referral, subscription' },
          { name: 'DTC Converts', count: 5100, revenue: '£204k', aov: '£40', action: 'Cross-sell, bundle, subscription nudge' },
          { name: 'Email Engaged', count: 8800, revenue: '£141k', aov: '£32', action: '2nd purchase incentive, DTC migration' },
          { name: 'Platform Loyalists', count: 18200, revenue: '£509k', aov: '£28', action: 'Email capture, DTC first-order offer' },
          { name: 'One-and-Done', count: 102900, revenue: '£2.06M', aov: '£20', action: 'Win-back or suppress — low ROI' },
          { name: 'Lapsed TikTok', count: 9900, revenue: '£0', aov: '£0', action: 'Retarget on platform or suppress' },
        ],
        dataSummary: '148k total customers. 121k are platform-only buyers — no email, no DTC account, invisible to owned CRM. Only 18k email subscribers (12% of base) but LTV of £94 — 3.4x the average. Owned Champions (4,100) generate £385k at £94 AOV with 38% repeat. Platform Loyalists (18,200) are frequent TikTok buyers not yet on email — highest priority for owned channel migration.',
      },
      benchmarks: {
        kpis: [
          { label: 'Platform dependency', value: '78% / 45%', delta: 'High risk vs category', sentiment: 'neg' },
          { label: 'Owned channel share', value: '18% / 42%', delta: '-24pp gap', sentiment: 'neg' },
          { label: 'Email / customers', value: '12% / 28%', delta: 'Underleveraged', sentiment: 'neg' },
          { label: 'DTC repeat purchase', value: '38% / 38%', delta: 'At benchmark', sentiment: 'pos' },
          { label: 'DTC AOV', value: '£41 / £38', delta: 'Above average', sentiment: 'pos' },
        ],
        metrics: [
          { metric: 'Platform revenue dependency', company: '78%', category: '45%', top: '28%', gap: 'Severe' },
          { metric: 'Owned channel revenue share', company: '18%', category: '42%', top: '61%', gap: 'Severe' },
          { metric: 'Email list as % of customers', company: '12%', category: '28%', top: '44%', gap: 'Significant' },
          { metric: 'DTC website CVR', company: '0.4%', category: '2.2%', top: '3.8%', gap: 'Significant' },
          { metric: 'Customer repeat rate', company: '19%', category: '38%', top: '54%', gap: 'Significant' },
          { metric: 'Platform fee as % of GMV', company: '8%', category: '4%', top: '2%', gap: 'Above average' },
          { metric: 'DTC repeat purchase rate', company: '38%', category: '38%', top: '54%', gap: 'At benchmark' },
          { metric: 'DTC average order value', company: '£41', category: '£38', top: '£62', gap: 'Above average' },
        ],
        dataSummary: 'Platform dependency 78% vs 45% category average (Severe). Owned channel share 18% vs 42% (Severe). Email penetration 12% vs 28% (Significant). DTC CVR 0.4% vs 2.2% (Significant). DTC repeat purchase rate 38% — at benchmark. DTC AOV £41 vs £38 — above benchmark. Strong product-market fit but dangerous platform dependency and weak owned channel infrastructure.',
      },
    },
  },
};
